# Generated by Django 2.1 on 2018-09-07 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('closed', 'Closed'), ('working', 'Working'), ('spam', 'Spam')], default='new', max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form Enquiry',
                'verbose_name_plural': 'Contact Form Enquiries',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('unpublished', 'Unpublished'), ('published', 'Published')], db_index=True, max_length=50)),
                ('venue', models.CharField(choices=[('events', 'Events'), ('training-center', 'Training Center'), ('hotel-3-star', '3 Star'), ('hotel-4-star', '4 Star'), ('hotel-5-star', '5 Star'), ('business-center', 'Business Center')], max_length=50)),
                ('category', models.CharField(choices=[('serviced-offices', 'Serviced Offices'), ('banquet-halls', 'Banquet Halls'), ('coworking-spaces', 'Co-working Spaces'), ('meeting-rooms', 'Meeting Rooms')], max_length=50)),
                ('layout', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('banquet', 'Banquet'), ('boardroom', 'Boardroom'), ('cabaret', 'Cabaret'), ('classroom', 'Classroom'), ('cocktail', 'Cocktail'), ('theater-auditorium', 'Theater/Auditorium'), ('ushaped', 'U Shaped'), ('vshaped', 'V Shaped')], max_length=79)),
                ('title', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=600)),
                ('description', models.TextField(blank=True)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('parking', models.CharField(blank=True, max_length=100)),
                ('deposit', models.CharField(blank=True, max_length=100)),
                ('minimum_terms', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('area', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('capacity_min', models.PositiveIntegerField()),
                ('capacity_max', models.PositiveIntegerField()),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Connectors'), (1, 'Flipchart'), (2, 'Metro'), (3, 'Mic/Audio Equipment'), (4, 'Printers'), (5, 'Projector Screen'), (6, 'Stationary'), (7, 'Tea/Coffee'), (8, 'Video Conferencing'), (9, 'Whiteboard'), (10, 'Wifi')], max_length=22)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('I', 'Image'), ('F', 'Floor Plans'), ('V', 'Video')], max_length=50)),
                ('url', s3direct.fields.S3DirectField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portal.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('is_enquiry', models.BooleanField(default=True, verbose_name='Enquiry')),
                ('status', models.CharField(choices=[('new', 'New'), ('closed', 'Closed'), ('working', 'Working'), ('spam', 'Spam')], default='new', max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Listing')),
            ],
            options={
                'verbose_name': 'Listing Enquiry',
                'verbose_name_plural': 'Listing Enquiries',
            },
        ),
        migrations.CreateModel(
            name='ListingPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_prefix', models.CharField(blank=True, choices=[('', ''), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=50)),
                ('frequency', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='portal.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('email_enquiries', models.PositiveIntegerField(default=0)),
                ('call_enquiries', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('is_city', models.BooleanField(default=False)),
                ('is_location', models.BooleanField(default=False)),
                ('is_sublocation', models.BooleanField(default=False)),
                ('latitude', models.FloatField(max_length=15, null=True)),
                ('longitude', models.FloatField(max_length=15, null=True)),
                ('status', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Location')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='loc_city',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.Location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='loc_location',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.Location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='loc_sub_location',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.Location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='listingstats',
            unique_together={('date', 'listing')},
        ),
    ]
