# Generated by Django 2.1.1 on 2018-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpricing',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('unpublished', 'Unpublished'), ('published', 'Published')], db_index=True, max_length=50),
        ),
    ]
