# Generated by Django 2.1.1 on 2018-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180907_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingasset',
            name='asset_type',
            field=models.CharField(choices=[('I', 'Image')], max_length=50),
        ),
    ]
