# Generated by Django 2.1.1 on 2018-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180907_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_daily',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_hourly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_weekly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
