# Generated by Django 2.1.1 on 2018-09-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180907_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price_year',
            new_name='price_yearly',
        ),
    ]
