# Generated by Django 2.1.1 on 2018-09-08 10:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20180907_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Connectors'), (1, 'Flipchart'), (2, 'Metro'), (3, 'Mic/Audio Equipment'), (4, 'Printers'), (5, 'Projector Screen'), (6, 'Stationary'), (7, 'Tea/Coffee'), (8, 'Video Conferencing'), (9, 'Whiteboard'), (10, 'Wifi'), (11, 'Parking')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listingasset',
            name='asset_type',
            field=models.CharField(choices=[('image', 'Image')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listingpricing',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50),
        ),
    ]
