# Generated by Django 2.1.1 on 2019-07-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20180908_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusenquiry',
            options={'verbose_name': 'Contact Form Inquiry', 'verbose_name_plural': 'Contact Form Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'space', 'verbose_name_plural': 'spaces'},
        ),
        migrations.AlterModelOptions(
            name='listingasset',
            options={'verbose_name': 'space asset', 'verbose_name_plural': 'space assets'},
        ),
        migrations.AlterModelOptions(
            name='listingenquiry',
            options={'verbose_name': 'Space Inquiry', 'verbose_name_plural': 'Space Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='listingpricing',
            options={'verbose_name': 'space pricing', 'verbose_name_plural': 'spaces pricings'},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
    ]
