# Generated by Django 2.1.1 on 2019-07-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190708_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingenquiry',
            name='is_enquiry',
        ),
    ]
