# Generated by Django 2.1.1 on 2019-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_listingenquiry_is_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingasset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
