# Generated by Django 2.1.1 on 2019-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_listingasset_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listingpricing',
            name='frequency_prefix',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50),
        ),
    ]
