# Generated by Django 2.1.1 on 2020-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190915_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusenquiry',
            name='contact_type',
            field=models.CharField(choices=[('listvenueform', 'List Venue Form'), ('contactform', 'Contact Us Form')], default='contactform', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('serviced-offices', 'Serviced Offices'), ('meeting-rooms', 'Meeting Rooms')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='venue',
            field=models.CharField(choices=[('business-center', 'Business Center')], max_length=50),
        ),
    ]
