# Generated by Django 2.1.1 on 2021-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200226_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('form', models.CharField(choices=[('listing', 'Listing'), ('contact', 'Contact')], default='listing', max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spam',
                'verbose_name_plural': 'Spams',
            },
        ),
    ]
