# Generated by Django 2.1 on 2018-09-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180907_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='logo',
        ),
    ]
