# Generated by Django 2.1.1 on 2018-09-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180907_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
