# Generated by Django 2.1.1 on 2018-09-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180907_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='account.Company'),
        ),
    ]
