# Generated by Django 2.1.1 on 2018-09-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180907_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
