# Generated by Django 2.1.1 on 2019-07-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_company_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('amount', models.SmallIntegerField(default=0)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank transfer', 'Bank Transfer'), ('others', 'Others')], default='cash', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.Company')),
            ],
        ),
    ]
