# Generated by Django 2.1.1 on 2019-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_companypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('business center', 'Business Center'), ('hotel', 'Hotel'), ('outdoor', 'Outdoor'), ('stadium', 'Stadium'), ('restaurant', 'Restaurant'), ('conference centers', 'Conference Centers'), ('club and bars', 'Club and/or Bars'), ('art gallery', 'Art Galleries'), ('others', 'Others')], default='others', max_length=30),
        ),
    ]
