# Generated by Django 2.1.1 on 2019-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_company_company_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='company',
            name='inquiry_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
