# Generated by Django 2.1.1 on 2019-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190722_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='sms_mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
