# Generated by Django 2.1.1 on 2019-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190929_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
