"""
Django settings for shapp project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import uuid

from django.utils.text import slugify
from django.core.exceptions import ImproperlyConfigured

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

from .jet_theme_config import *  # JET Admin theme configurations

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1g*j5_670het@@q3d56s7@4%lo^@+gpe74wu=9!((q8j046%+9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

if not DEBUG:
    sentry_sdk.init(
        dsn="https://f10d388ebfef4b778879b56f7528cefb@sentry.io/1765770",
        integrations=[DjangoIntegration()]
    )

# Application definition

INSTALLED_APPS = [
    # 'jet.dashboard',
    # 'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',

    'portal',
    'account',
    'speedyblog',

    # Thirdparty apps
    'htmlmin',
    'sendwithus',
    's3direct',
    # 'runas',
    'el_pagination',
    'markdown_deux',
    'pagedown',
    'multiselectfield',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'runas.middleware.RunAsMiddleware',
]

EXCLUDE_FROM_MINIFYING = ('^s3direct/', '^admin/')

ROOT_URLCONF = 'shapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'shapp.context_processors.settings_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'shapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SENDWITHUS_TEMPLATES = {
    'LISTING_ENQUIRY': 'tem_BTHWXChYfPw6D4Jw6vMMY9vQ',
    'LISTING_ENQUIRY_AGENT': 'tem_xYD9tTcFrhj3fHWpwygbSTGC',
    'ACTIVATION_LINK': 'tem_DVDSMrWSCTPCBRRRHq43fVVd',
    'CONTACT_US': 'tem_wCryT3pygjRKcrbMVkYX8wjD',
    'BASIC': 'tem_WKTmt8MhwbtyfMdxmxGTdjJ7'
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


def get_filename_func(path_prefix=None):
    """Returns a function (closure) that generates uuid4 based file names for uploading to AWS S3.

    It takes an optional path prefix that allows files to be placed in folders in the bucket. Used to generate filenames
    for files uploaded to S3 via the S3 Direct library.
    """

    def _wrapped(filename):
        extension = ''
        file_parts = os.path.splitext(filename)
        file_name = file_parts[0]

        if len(file_parts) > 1:
            extension = file_parts[-1]

        final_file_name = "{slugified_name}-{random_string}{extension}".format(
            slugified_name=slugify(file_name),
            random_string=uuid.uuid4().hex[:5],
            extension=extension)

        if path_prefix:
            final_file_name = '{}/{}'.format(path_prefix, final_file_name)

        return final_file_name

    return _wrapped


DEFAULT_EMAIL = 'tech@idealspaces.com'

S3DIRECT_DESTINATIONS = {
    'listing_assets': {
        'key': get_filename_func('listing_assets'),
        'bucket': 'idealspaces-listing-assets',
        'allowed': ['image/jpeg', 'image/png'],
        'acl': 'public-read',  # Defaults to 'public-read'
        'cache_control': 'max-age=2592000',  # Default no cache-control
        'content_length_range': (5000, 20000000),  # Default allow any size
    }
}

# AWS S3 Configurations for S3 Direct
S3DIRECT_REGION = 'ap-southeast-1'
S3DIRECT_URL = 'https://ap-southeast-1.amazonaws.com'

AWS_STORAGE_BUCKET_NAME = ''

S3DIRECT_DESTINATIONS = {
    'listing_assets': {
        # REQUIRED
        'key': get_filename_func(),

        # OPTIONAL
        'acl': 'public-read',
        'auth': lambda u: u.is_active,  # Default allow anybody to upload
        'allowed': ['image/jpeg', 'image/png'],  # Default allow all mime types
        # 'allowed_extensions': ('.jpg', '.jpeg', '.png'),  # Defaults to all extensions
        'bucket': 'idealspacescom-listing-assets',  # Default is 'AWS_STORAGE_BUCKET_NAME'
        'cache_control': 'max-age=2592000',  # Default no cache-control
    },
    'user_assets': {
        # REQUIRED
        'key': get_filename_func(),

        # OPTIONAL
        'acl': 'public-read',
        'auth': lambda u: u.is_active,  # Default allow anybody to upload
        'allowed': ['image/jpeg', 'image/png', 'application/pdf'],  # Default allow all mime types
        # 'allowed_extensions': ('.jpg', '.jpeg', '.png', '.pdf', '.doc', '.docx'),  # Defaults to all extensions
        'bucket': 'idealspacescom-user-assets',  # Default is 'AWS_STORAGE_BUCKET_NAME'
        'cache_control': 'max-age=2592000',  # Default no cache-control
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'common_static'),
]

LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/account/'
LOGOUT_REDIRECT_URL = '/account/login/'

AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''

# Google ReCaptcha
CAPTCHA_SITE_KEY = '6LelB7sUAAAAAC9ml-DXcIRrVIWT_deBZZhZ6CdQ'
CAPTCHA_SECRET_KEY = '6LelB7sUAAAAAPJqmNYIPjEJjV5h5TLQXk0PBkj3'

GOOGLE_MAP_API_KEY = 'AIzaSyDnQoy7P4Kk97l4Sh_f2fFPw_uev5YOn1s'
GOOGLE_URL_SHORTNER = 'AIzaSyDnQoy7P4Kk97l4Sh_f2fFPw_uev5YOn1s'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'idealspaces.com'
EMAIL_HOST_PASSWORD = '<7M5Y(A4+A'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'IdealSpaces.com <noreply@idealspaces.com>'
ADMIN_EMAIL = 'aghahasanraza@gmail.com'
ADMIN_EMAIL2 = 'itshemani@gmail.com'

FACEBOOK_URL = 'https://www.facebook.com/idealspacescom/'
TWITTER_URL = 'https://twitter.com/idealspacescom'
LINKEDIN_URL = 'https://www.linkedin.com/'
INSTAGRAM_URL = 'https://www.instagram.com/idealspacescom/'
GOOGLEPLUS_URL = 'https://www.googleplus.com/'

try:
    from .localsettings import *
except ImportError:
    pass
    # raise ImproperlyConfigured('No localsettings.py found. You need that file to start the application.')
